### ISSUE TITLE
Not an Issue:  A Huge THANK YOU Instead!!!!!!!!!!!

### ISSUE THREAD

**Issue by ccclapp** [StarshipEngineer/OpenVPN-Setup#32]
Hi 
I just installed from your script on a new RPi2 running the newest Jessie.  It was flawless!!!  I have been struggling with no success doing a self-install following various tutorials, including the outdated Part 1-2 credited in your readme. **Your install was perfect and Soooooo easy**.  I am jumping over to the paypal link now...Thanks!

PS:  My one request is if you could explain or add the ability to run OpenVpn on startup.  Is it possible you would add those commands in your readme?  Thanks

**Comment by StarshipEngineer** [comment]
I'm glad that you've found the script to be helpful, it's great to hear! Thank you for letting me know, I've been working on adapting it to Jessie for some time, and it's helpful to know it works for other users. Thank you as well for the contribution, it is very much appreciated!

The install script now adds to rc.local a command to run OpenVPN on boot. You can also make this modification yourself by opening rc.local with nano and adding the following line after the reference to /etc/openvpn-firewall-rules.sh:

sudo service openvpn start

To start the daemon manually, simply type the same command into the command line.

**Comment by ccclapp** [comment]
Hi Dan

Thanks for the command to run on startup!!  Question:  i. I understand cr.local has issues with some startup commands (does not start as early??) on Jessie, so just checking that via rc it will start fine. ii, So by your command, I gather OVPN runs as a service and the rc is simply starting it, I assume that means I can stop/restart, etc with the same commands as for other services, correct?

You did an excellent job with this!  I hope you don’t mind, I posted a link in a few places where others had done how-to’s, which were not current and many users were trying to figure out how to do a manual install.

May I ask a few questions / make a few suggestions?...


-          I expect many others will want to use your approach v the other (not very good and/or outdated) how-to’s.  You will likely get other noobs, like me, who will have questions.  Thus, you may want to start a Q&A section on your github, if that is possible.  Ideally where others can reply with answers, so you don’t need to do all of the hand holding.  Another way would be to start a new thread on RPi Org forums https://www.raspberrypi.org/forums/ or somewhere similar.  If you prefer, I can do that for you.  If so, you should add a link in your readme, so everyone trying to install will get to the dedicated forum string and vice a versa (link in string to github).

-          If one wants to add another server/client (for use if the pi is in another location and/or duplicating SD card to run on other RPi’s, can this be done, or do you suggest removing OVPN and then re-creating

-          As stated I’m new at this, but notice some network resources don’t show up via the VPN, is that the nature of the beast?  Examples in the realm of home automation and audio/video control include trying to run the Sonos desktop app via the VPN, connecting to a java UP into a home automation controller, connecting to the Harmony (remote control) desktop UI and printing on at least one printer.  Is this to be expected?

I guess that’s it, but a quick example of the myriad of questions users will have, now that you’ve cracked the nut on VPN for all!! ;-)

Thanks again!!!

PS:  If you do get a forum, Q&A, blog etc going for this, I am happy to post giving my experience/opinion of your solution and encouraging others to contribute via paypal.  If you get it up, please shoot me an email so I can chime in.

Caleb C. Clapp
President
Cushing Housing Corp
617-721-9111
caleb@cushingco.net<mailto:caleb@cushingco.net>

**Comment by StarshipEngineer** [comment]
Thanks for your interest and enthusiasm! I’m happy when people get mileage out of this project, and to share access to it with as many people as possible. I appreciate your sharing of the project in other forums and encouragement for monetary contributions! I do emphasize though that the script was mostly just a learning experience and I hope to provide the same for others, as well as something they might have some practical use for. I put in the option for contributions just because I could use the money. I’ll try to tackle your questions in order!
For starters, I’m not overly familiar with rc.local, most of my experience on the Pi has been with Raspbian Wheezy, and it wasn’t something that came up for me there;  this is my first project on Jessie. However, I have not had issues with rc.local for this purpose. The fix I added works for me, and allows rc.local to start the openvpn service on boot. To my understanding, OpenVPN is running as a service and will respond as such to general commands for services should you wish to stop, restart, or something else.
I will be looking into starting a forum on Github or the Raspberry Pi forums. The user base for this project has grown significantly since I uploaded the original script and it's been difficult to personally assist every user. I appreciate the suggestion and offer, and will have a go at it and let you know how it goes.
Regarding the question on additional servers, if I understand what you're interested in, I’d probably recommend just rerunning the script on the new machine. You could make an image of the configured system, and then burn it to a new microSD card (I do this for backups), but you would have to manually edit the server's public IP address in the key generation default file. More importantly, I’d also make sure you don't have copies of identical keys and OVPNs on more than one machine for security reasons, but even then you would still have two or more identical certificate authorities. I'm not a security expert, but I’d rather take the short time to run the script again. If you're simply moving the same server, I think editing the public IP to the new address in the default file would be fine.
Network issues may depend on your network architecture, and I'm afraid I don't have much experience there. I can access other devices fine on my home network, including a printer and other Pi’s via SSH. I just have my server plugged into my router, and pretty much everything on my local network is accessible when I connect to the VPN. I can't think of a reason other things wouldn't work, but wouldn't know where to start if they didn't.

If I get the forum going, hopefully there will be people with more experience with these issues to chime in.

**Comment by ccclapp** [comment]
Thanks for taking the time to go through my questions. Sorry to pepper you. Again, great script.

Yes, my point about opening a thread on an existing forum is that other users can help answer questions and not have everything directed to you. On the other hand I suppose if you start that thread people will be inclined to ask you.  Again, only if it helps deflect a bit for you, I could start a thread and link to your site and you could subscribe and chime in when you want. I'm only offering to be helpful not trying to do anymore than that.

All the best

Caleb C. Clapp
President
Cushing Housing Corp
caleb@cushingco.net<mailto:caleb@cushingco.net>
617-721-9111<tel:617-721-9111>
Sent from my mobile device

On Feb 20, 2016, at 10:02 PM, Dan Shuman <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your interest and enthusiasm! I’m happy when people get mileage out of this project, and to share access to it with as many people as possible. I appreciate your sharing of the project in other forums and encouragement for monetary contributions! I do emphasize though that the script was mostly just a learning experience and I hope to provide the same for others, as well as something they might have some practical use for. I put in the option for contributions just because I could use the money. I’ll try to tackle your questions in order!
For starters, I’m not overly familiar with rc.local, most of my experience on the Pi has been with Raspbian Wheezy, and it wasn’t something that came up for me there; this is my first project on Jessie. However, I have not had issues with rc.local for this purpose. The fix I added works for me, and allows rc.local to start the openvpn service on boot. To my understanding, OpenVPN is running as a service and will respond as such to general commands for services should you wish to stop, restart, or something else.
I will be looking into starting a forum on Github or the Raspberry Pi forums. The user base for this project has grown significantly since I uploaded the original script and it's been difficult to personally assist every user. I appreciate the suggestion and offer, and will have a go at it and let you know how it goes.
Regarding the question on additional servers, if I understand what you're interested in, I’d probably recommend just rerunning the script on the new machine. You could make an image of the configured system, and then burn it to a new microSD card (I do this for backups), but you would have to manually edit the server's public IP address in the key generation default file. More importantly, I’d also make sure you don't have copies of identical keys and OVPNs on more than one machine for security reasons, but even then you would still have two or more identical certificate authorities. I'm not a security expert, but I’d rather take the short time to run the script again. If you're simply moving the same server, I think editing the public IP to the new address in the default file would be fine.
Network issues may depend on your network architecture, and I'm afraid I don't have much experience there. I can access other devices fine on my home network, including a printer and other Pi’s via SSH. I just have my server plugged into my router, and pretty much everything on my local network is accessible when I connect to the VPN. I can't think of a reason other things wouldn't work, but wouldn't know where to start if they didn't.

If I get the forum going, hopefully there will be people with more experience with these issues to chime in.

**Comment by StarshipEngineer** [comment]
No worries, it's no bother. I started a forum thread on RaspberryPi.org and put a link in the Readme to direct people there. If you have anything you'd like to add to the thread as a user, you're welcome to. People will probably be more willing to chime in if they see people already active there. Thanks for the suggestion!

**Comment by ccclapp** [comment]
Hi,

Just letting you know you have lots of comments, questions etc not e RPi forum you started. Any chance you will reply over there to those?

Thanks

**Comment by StarshipEngineer** [comment]
I've been keeping an eye on the forum thread, and have been researching the port issue some users have been having. I likely won't be posting much until I have a concrete solution or ideas for fixing a problem however. I don't have a lot of time, and part of why I started the forum was so users had a chance to bounce ideas off each other and come up with answers or fixes with each other, rather than personally responding to every user.
